from . import res_partner_inherit
from . import operational_record_line
from . import cylinder_survey
from . import cylinder_image
from . import cylinder_survey_line
from . import purchase_order
from . import cylinder_options
from . import cylinder_material
from . import crm_decision
from . import cylinder_group
from . import sale_order_smart
from . import cylinder_section
from . import hr_department_inherit
from . import apu_survey
from . import apu_survey_line
from . import cylinder_accessory
from . import apu_survey_actions
from . import pricelist_conect
from . import sale_order_line_inherit
from . import apu_survey_margins